name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET 9.0.100
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.100'

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test --configuration Release

      # Skapa en zip-fil för din applikation
      - name: Publish Application
        run: |
          dotnet publish -c Release -o ./publish
          zip -r myapp.zip ./publish

      # Deploy to AWS Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          region: 'eu-north-1'
          application_name: 'CryptoAPI'
          environment_name: 'CryptoAPI-env'
          version_label: 'v1.0-${GITHUB_SHA}'  # Unikt versionsnamn baserat på Git commit SHA
          zip_file: 'myapp.zip'  # Den zip-fil vi skapade i förra steget
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
